apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-config-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.com:developers.edisaac/devops/argocd-configuration.git
    targetRevision: SNAPSHOT
    path: dev/argocd
  destination:
    name: dev-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
