apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.com:developers.edisaac/devops/kubernetes-configuration.git
    targetRevision: SNAPSHOT
    path: dev/apps/keycloak
  destination:
    name: dev-cluster
    namespace: dev
  syncPolicy:
    automated:
      prune: true
