apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:edisaac/kubernetes-configuration.git
    targetRevision: SNAPSHOT
    path: dev/apps/springboot
  destination:
    name: dev-cluster
    namespace: dev
  syncPolicy:
    automated:
      prune: true
