apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@gitlab.com:developers.edisaac/devops/kubernetes-configuration.git
    targetRevision: RELEASE
    path: qa/config/ingress
  destination:
    name: qa-cluster
    namespace: qa
  syncPolicy:
    automated:
      prune: true
