apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-config-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:edisaac/argocd-configuration.git
    targetRevision: RELEASE
    path: qa/argocd
  destination:
    name: qa-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
